#Enabling Multipart
spring.servlet.multipart.enabled=true
#Max size
spring.servlet.multipart.max-file-size=300MB
#threshold after file are writen to disk
spring.servlet.multipart.file-size-threshold=1KB

spring.datasource.name=d1;
spring.datasource.url=jdbc:mysql://localhost:3306/springjpa
spring.datasource.username=root
spring.datasource.password=Yash@#123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


